name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter 3.22.1 with Dart 3.8.1
      run: |
        git clone https://github.com/flutter/flutter.git --branch 3.22.1 --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_ENV
        export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
        flutter --version

    - name: Run Flutter doctor
      run: flutter doctor

    - name: Install dependencies
      run: |
        export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
        flutter pub get

    - name: Build APK
      run: |
        export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
        flutter build apk --release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bonas-apk
        path: build/app/outputs/flutter-apk/app-release.apk
