name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Flutter SDK manually
      run: |
        git clone https://github.com/flutter/flutter.git --branch 3.22.0 --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

    - name: Enable Flutter
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bonas-apk
        path: build/app/outputs/flutter-apk/app-release.apk
